# Project Name
TARGET = firmware

# Sources
CPP_SOURCES = firmware.cpp
CPP_SOURCES += Discomfort.cpp
CPP_SOURCES += Folder.cpp

# Library Locations
LIBDAISY_DIR = ../../DaisyExamples/libDaisy/
DAISYSP_DIR = ../../DaisyExamples/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
